# Site settings
baseurl = "https://data4sci.github.io/fotoalbum/"
languageCode = "cs-CZ"
title = "Svatba Vendy & Jirka"
theme = "photo-grid"

# Enter your tracking code to enable Google Analytics
# googleAnalytics = "UA-XXXXXXXX-Y"x

[params]
    # Meta
    no_exif = true
    title = "Svatba Vendy & Jirka"
    subtitle = "" #"12. září 2020 | Belaria Resort"
    author = "Robik & Ka"
    description = "Commodo aute fugiat reprehenderit quis minim adipisicing ex exercitation."
    keywords = "Svatba, Wedding, Photo, Gallery"

    # Body background and  text color
    bodybgcolor = "#3d3d3d" #"#DADADB" #"#6A6C6E"#
    bodytextcolor = "#f2f2f2"

    # Footer text
    footertext = "Made with love by [Karin](https://kotalka.github.io/KARIKO/) a Rob. <br> (C) 2020"
